CREATE TABLE matchdata (
	couple_id VARCHAR PRIMARY KEY NOT NULL,
	f_age FLOAT,
 	f_imprace FLOAT,
	f_attr FLOAT, 
	f_sinc FLOAT,
	f_intel FLOAT,
	f_fun FLOAT,
	f_amb FLOAT,
	f_race FLOAT,
	f_intrace FLOAT,
	m_age FLOAT,
	m_imprace FLOAT,
	m_attr FLOAT,
	m_sinc FLOAT,
	m_intel FLOAT,
	m_fun FLOAT,
	m_amb FLOAT,
	m_race FLOAT,
	samerace SMALLINT,
	match SMALLINT,
	m_intrace FLOAT
);
CREATE TABLE "Users" (
	iid int PRIMARY KEY NOT NULL,
	firstname varchar,
	lastname varchar,
	password varchar,
	gender int,
	age float,
	screenname varchar,
	email varchar,
	photo varchar,
	race int,
	imprace float,
	attr float,
	sinc float,
	intel float,
	fun float,
	amb float);

